spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/spring_boot_security_web
    username: root
    password: root

springdoc:
  swagger-ui:
    path=/swagger-ui.html

admin.default:
  username: admin
  password: admin

jwt:
  signing-secret: some-secret

api-key:
  clients:
    client-a: abc
    client-b: 111