spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/spring_boot_security_web
    username: root
    password: root
  freemarker:
    template-loader-path: classpath:/templates/
    suffix: .ftl

springdoc:
  swagger-ui:
    path=/swagger-ui.html

admin.default:
  username: admin
  password: admin